### ISSUE TITLE
Update to v1.2.0

### ISSUE THREAD

**Issue by tell-k** [woothee/woothee-python#10]
@tagomoris 

I've updated woothee-python to reference woothee-ruby.

https://pypi.python.org/pypi/woothee/1.2.0

* Add support for Twitterbot
* Add support for webviews of mobile devices
* Add support for Windows 10 and Edge browser
* Add support for BlackBerry10

Please feel free to try it :)

**Comment by yuya-takeyama** [comment]
:tada:

**Comment by tell-k** [comment]
:smile:  thanks!
