### ISSUE TITLE
Register to PyPI

### ISSUE THREAD

**Issue by yuya-takeyama** [woothee/woothee-python#6]
Registration to PyPI helps users to install woothee-python easily.
http://ja.stackoverflow.com/questions/1863/%E6%A4%9C%E7%B4%A2%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%B3%E3%81%AA%E3%81%A9%E3%81%AE%E3%83%AD%E3%83%9C%E3%83%83%E3%83%88%E3%82%92%E5%88%A4%E5%AE%9A%E3%81%99%E3%82%8Bpython%E3%83%A2%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB%E3%81%AF%E3%81%82%E3%82%8A%E3%81%BE%E3%81%99%E3%81%8B

Previously, @tell-k already has set up `setup.py`.
So remaining process is just below.

1. Register to PyPI
2. python setup.py register
3. python setup.py sdist upload

Testing environment is also available here.
https://testpypi.python.org/pypi
(I tested regisration of woothee to testpypi and just removed)

And this article helped me so much.
http://qiita.com/edvakf@github/items/d82cd7ab77ea2b88506c

**Comment by tell-k** [comment]
@yuya-takeyama
 
I have just finished to upload it.
https://pypi.python.org/pypi/woothee/
Please try it if you feel free.
Thx.

**Comment by yuya-takeyama** [comment]
Thanks for your work!
